routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SiteController@index')->name('welcome');
Route::get('/homepage','SiteController@homepage')->name('homepage');
Route::get('/product','SiteController@product')->name('product');
Route::get('/rnd','SiteController@rnd')->name('rnd');
Route::get('/oem','SiteController@oem')->name('oem');
Route::get('/contact','SiteController@contact')->name('contact');
Route::get('/story','SiteController@story')->name('story');
Route::get('/blogs','SiteController@blog')->name('blogs');
Route::get('/galleryshow','SiteController@galleryshow')->name('galleryshow');
Route::get('/albumshow/{album}','SiteController@albumshow')->name('albumshow');
Route::post('/contactmail','SiteController@contactmail')->name('contactmail');
Route::get('/loadproducts','SiteController@loadproducts')->name('loadproducts');
Route::post('/search','SiteController@search')->name('search');
Route::get('/thisyear','SiteController@thisyear')->name('thisyear');
Route::get('/pastyear','SiteController@pastyear')->name('pastyear');
Route::get('/nextyear','SiteController@nextyear')->name('nextyear');
Route::get('/jan/{blog}','SiteController@jan')->name('jan');
Route::get('/feb/{blog}','SiteController@feb')->name('feb');
Route::get('/mar/{blog}','SiteController@mar')->name('mar');
Route::get('/apr/{blog}','SiteController@apr')->name('apr');
Route::get('/may/{blog}','SiteController@may')->name('may');
Route::get('/jun/{blog}','SiteController@jun')->name('jun');
Route::get('/jul/{blog}','SiteController@jul')->name('jul');
Route::get('/aug/{blog}','SiteController@aug')->name('aug');
Route::get('/sep/{blog}','SiteController@sep')->name('sep');
Route::get('/oct/{blog}','SiteController@oct')->name('oct');
Route::get('/nov/{blog}','SiteController@nov')->name('nov');
Route::get('/dec/{blog}','SiteController@dec')->name('dec');
Route::get('/view/{blog}','SiteController@view')->name('view');

Route::get('/launched','SiteController@launched')->name('launched');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('blog', 'BlogController');
    Route::resource('brands', 'BrandsController');
    Route::resource('categories', 'CategoriesController'); 
    Route::resource('subcategories', 'SubCategoriesController'); 
    Route::resource('products', 'ProductController'); 
    Route::get('getSubCat/{id}', 'ProductController@GetSubCat');
    Route::put('productimage', 'ProductController@productimage')->name('products.productimage'); 
    Route::get('productimageset/{product}', 'ProductController@productimageset')->name('products.productimageset');
    Route::post('productstatus/{product}', 'ProductController@status')->name('products.status'); 
    Route::get('passwordreset', 'UsersController@passwordreset')->name('passwordreset'); 
    Route::get('changepwd/{user}', 'UsersController@changepwd')->name('changepwd'); 
    Route::get('ckeditor', 'CkeditorController@index');
    Route::post('ckeditor/upload', 'CkeditorController@upload')->name('ckeditor.upload');   

    Route::get('/album','AlbumController@index')->name('album.index');
    Route::get('/album-getdata','AlbumController@getdata')->name('album.getdata');
    Route::post('/album/add','AlbumController@add')->name('album.add');
    Route::post('/album/edit','AlbumController@edit')->name('album.edit');
    Route::post('/album/delete','AlbumController@delete')->name('album.delete');

    Route::get('album-images/{album}','GalleryController@images')->name('album.images');
    Route::post('dropzone/upload', 'GalleryController@upload')->name('dropzone.upload');
    Route::get('dropzone/fetch', 'GalleryController@fetch')->name('dropzone.fetch');
    Route::get('dropzone/delete', 'GalleryController@delete')->name('dropzone.delete');
    Route::get('getfile/{id}', 'GalleryController@getfile')->name('getfile');

});

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    protected $fillable=[
        'name','category_id',
    ];

    public function category(){
        return $this->belongsTo(Category::class);
    }
    
    public function products(){
        return $this->hasMany(Product::class,'subcategory_id');
    }
}

app/Http/Controllers/SubCategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\SubCategory;
use App\Http\Requests\Categories\CategoriesCreateController;
use App\Http\Requests\Categories\CategoriesUpdateController;

class SubCategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('subcategories.index')->with('subcategories',SubCategory::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('subcategories.create')->with('categories',Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriesCreateController $request)
    {

        $subcategory=SubCategory::create([
            'name'=>$request->name,
            'category_id'=>$request->category_id,
        ]);

        session()->flash('success','Sub Category Created Successfully');
        return redirect(route('subcategories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(SubCategory $subcategory)
    {
        return view('subcategories.create')->with('subcategory',$subcategory)->with('categories',Category::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriesUpdateController $request, SubCategory $subcategory)
    {
        $data=$request->only(['name','category_id']);

        $subcategory->update($data);

        session()->flash('success','Sub Category Updated Successfully');
        return redirect(route('subcategories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(SubCategory $subcategory)
    {
        if($subcategory->products->count() ==0){
            $subcategory->delete();
            session()->flash('success','Sub Category Deleted Successfully');
        }else{
            session()->flash('error','Sub Category Has Some Products');
        }

        return redirect(route('subcategories.index'));

    }




}

resources/views/subcategories/create.blade.php
@extends('layouts.app')

@section('content')


        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between g-3">
                <div class="nk-block-head-content">
                    <h2 class="nk-block-title page-title">{{ isset($subcategory)?'Update':'Add' }} Sub Category</h2>
                    <div class="nk-block-des text-soft">
                        * are required.
                    </div>
                </div>
                
                <div class="nk-block-head-content">
                    <ul class="nk-block-tools g-3">
                        <li class="nk-block-tools-opt">
                            <a href="{{ route('subcategories.index') }}" class="btn btn-primary">
                                <em class="icon ni ni-arrow-left"></em>
                                <span>Back</span>
                            </a>
                        </li>
                    </ul>
                </div><!-- .nk-block-head-content -->
            </div><!-- .nk-block-head -->
        </div><!-- .nk-block-head -->
            
        @include('partials.session')
        @include('partials.error')
        
        <div class="nk-block nk-block-lg">
            <div class="card card-bordered">
                <div class="card-inner">
                    <div class="card-head">
                        <h5 class="card-title">{{ isset($subcategory)?'Edit':'New' }} Sub Category Setup</h5>
                    </div>
                    <form action="{{ isset($subcategory)? route('subcategories.update',$subcategory->id):route('subcategories.store') }}" class="gy-3" class="is-alter form-validate" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if (isset($subcategory))
                            {{ method_field('PUT') }}
                        @endif
                        <div class="row g-4">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <div class="form-control-wrap">
                                        <select name="category_id" id="category_id" class="form-select" >
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}"
                                                    @if (isset($subcategory))
                                                        @if ($category->id==$subcategory->category_id)
                                                            selected
                                                        @endif
                                                    @endif
                                                    >{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-label" for="name">Sub Category Name *</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="name" id="name" value="{{ isset($subcategory)?$subcategory->name:old('name') }}">
                                    </div>
                                </div>
                            </div>

                    
                            <div class="col-12">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-primary"><em class="icon ni ni-save"></em><span>Save & Next</span> </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- .nk-block -->
@endsection

@section('script')
    <script type="text/javascript">
        CKEDITOR.replace('content', {
            filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
            filebrowserUploadMethod: 'form'
        });
    </script>
@endsection

@section('css')
    <script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
@endsection

resources/views/subcategories/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between g-3">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Sub Categoris</h3>
                <div class="nk-block-des text-soft">
                    <p>You have total {{$subcategories->count()}} sub categories.</p>
                </div>
            </div><!-- .nk-block-head-content -->
            <div class="nk-block-head-content">
                <ul class="nk-block-tools g-3">
                    <li>
                        <div class="drodown">
                            
                            <a href="{{ route('subcategories.create') }}" class="btn btn-primary">
                                <em class="icon ni ni-plus"></em>
                                <span>Add New Category</span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div><!-- .nk-block-head-content -->
        </div><!-- .nk-block-between -->
    </div><!-- .nk-block-head -->

    
    @include('partials.error')
    
    @include('partials.session')
    
    <div class="nk-block nk-block-lg">
        <div class="card card-preview">
            <div class="card-inner">
                <table class="datatable-init nk-tb-list nk-tb-ulist" data-auto-responsive="false" id="subcategories">
                    <thead>
                        <tr class="nk-tb-item nk-tb-head">
                            <th class="nk-tb-col "><span class="sub-text">#</span></th>
                            <th class="nk-tb-col"><span class="sub-text">Name</span></th>
                            <th class="nk-tb-col"><span class="sub-text">Category</span></th>
                            <th class="nk-tb-col tb-col-lg"><span class="sub-text">Created at</span></th>
                            <th class="nk-tb-col nk-tb-col-tools text-right">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $i=1;
                        @endphp
                        @foreach ($subcategories as $subcategory)
                            <tr class="nk-tb-item">
                                <td class="nk-tb-col tb-col-md">
                                    <span>{{ $i }}</span>
                                </td>
                                <td class="nk-tb-col">
                                    <div class="user-card">
                                        <div class="user-info">
                                            <span class="tb-lead">{{ substr($subcategory->name,0,25) }} <span class="dot dot-success d-md-none ml-1"></span></span>
                                        </div>
                                    </div>
                                </td>
                                <td class="nk-tb-col">
                                    <div class="user-card">
                                        <div class="user-info">
                                            <span class="tb-lead">{{ substr($subcategory->category->name,0,25) }} <span class="dot dot-success d-md-none ml-1"></span></span>
                                        </div>
                                    </div>
                                </td>
                                <td class="nk-tb-col tb-col-md">
                                    <span>{{ $subcategory->created_at->format('d M Y') }}</span>
                                </td>
                                <td class="nk-tb-col nk-tb-col-tools">
                                    <ul class="nk-tb-actions gx-1">
                                        <li>
                                            <div class="drodown">
                                                <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <ul class="link-list-opt no-bdr">
                                                        <li><a href="{{ route('subcategories.edit',$subcategory->id) }}"><em class="icon ni ni-eye-alt"></em><span>Edit</span></a></li>
                                                        <li><a role="button" onclick="handleDelete({{$subcategory->id}})"><em class="icon ni ni-trash"></em><span>Remove</span></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </td>
                            </tr><!-- .nk-tb-item  -->
                            @php
                                $i++;
                            @endphp
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div><!-- .card-preview -->
    </div> <!-- nk-block -->

    <!-- Modal Alert -->
    <div class="modal fade" tabindex="-1"  role="dialog" id="deleteModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="post" id="deleteform">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
                <div class="modal-content">
                    <a href="#" class="close" data-dismiss="modal"><em class="icon ni ni-cross"></em></a>
                    <div class="modal-body modal-body-lg text-center">
                        <div class="nk-modal">
                            <em class="nk-modal-icon icon icon-circle icon-circle-xxl ni ni-alert bg-warning"></em>
                            <h4 class="nk-modal-title">Delete Category!</h4>
                            <div class="nk-modal-text">
                                <div class="caption-text">Are you sure, you want to <strong>delete</strong> this sub category ?</div>
                                <span class="sub-text-sm">This action can not be revert.</span>
                            </div>
                            <div class="nk-modal-action">
                                <button type="button" class="btn-lg btn-mw btn-primary" data-dismiss="modal">No, Go back</button>
                                <button type="submit" class="btn-lg btn-mw btn-danger">Yes, Delete</button>
                            </div>
                        </div>
                    </div><!-- .modal-body -->
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function handleDelete(id){
            var form= document.getElementById('deleteform')
            form.action='/subcategories/'+id
            $('#deleteModal').modal('show')
        }

    </script> 
@endsection