routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SiteController@index')->name('welcome');
Route::get('/homepage','SiteController@homepage')->name('homepage');
Route::get('/product','SiteController@product')->name('product');
Route::get('/rnd','SiteController@rnd')->name('rnd');
Route::get('/oem','SiteController@oem')->name('oem');
Route::get('/contact','SiteController@contact')->name('contact');
Route::get('/story','SiteController@story')->name('story');
Route::get('/blogs','SiteController@blog')->name('blogs');
Route::get('/galleryshow','SiteController@galleryshow')->name('galleryshow');
Route::get('/albumshow/{album}','SiteController@albumshow')->name('albumshow');
Route::post('/contactmail','SiteController@contactmail')->name('contactmail');
Route::get('/loadproducts','SiteController@loadproducts')->name('loadproducts');
Route::post('/search','SiteController@search')->name('search');
Route::get('/thisyear','SiteController@thisyear')->name('thisyear');
Route::get('/pastyear','SiteController@pastyear')->name('pastyear');
Route::get('/nextyear','SiteController@nextyear')->name('nextyear');
Route::get('/jan/{blog}','SiteController@jan')->name('jan');
Route::get('/feb/{blog}','SiteController@feb')->name('feb');
Route::get('/mar/{blog}','SiteController@mar')->name('mar');
Route::get('/apr/{blog}','SiteController@apr')->name('apr');
Route::get('/may/{blog}','SiteController@may')->name('may');
Route::get('/jun/{blog}','SiteController@jun')->name('jun');
Route::get('/jul/{blog}','SiteController@jul')->name('jul');
Route::get('/aug/{blog}','SiteController@aug')->name('aug');
Route::get('/sep/{blog}','SiteController@sep')->name('sep');
Route::get('/oct/{blog}','SiteController@oct')->name('oct');
Route::get('/nov/{blog}','SiteController@nov')->name('nov');
Route::get('/dec/{blog}','SiteController@dec')->name('dec');
Route::get('/view/{blog}','SiteController@view')->name('view');

Route::get('/launched','SiteController@launched')->name('launched');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('blog', 'BlogController');
    Route::resource('brands', 'BrandsController');
    Route::resource('categories', 'CategoriesController'); 
    Route::resource('subcategories', 'SubCategoriesController'); 
    Route::resource('products', 'ProductController'); 
    Route::get('getSubCat/{id}', 'ProductController@GetSubCat');
    Route::put('productimage', 'ProductController@productimage')->name('products.productimage'); 
    Route::get('productimageset/{product}', 'ProductController@productimageset')->name('products.productimageset');
    Route::post('productstatus/{product}', 'ProductController@status')->name('products.status'); 
    Route::get('passwordreset', 'UsersController@passwordreset')->name('passwordreset'); 
    Route::get('changepwd/{user}', 'UsersController@changepwd')->name('changepwd'); 
    Route::get('ckeditor', 'CkeditorController@index');
    Route::post('ckeditor/upload', 'CkeditorController@upload')->name('ckeditor.upload');   

    Route::get('/album','AlbumController@index')->name('album.index');
    Route::get('/album-getdata','AlbumController@getdata')->name('album.getdata');
    Route::post('/album/add','AlbumController@add')->name('album.add');
    Route::post('/album/edit','AlbumController@edit')->name('album.edit');
    Route::post('/album/delete','AlbumController@delete')->name('album.delete');

    Route::get('album-images/{album}','GalleryController@images')->name('album.images');
    Route::post('dropzone/upload', 'GalleryController@upload')->name('dropzone.upload');
    Route::get('dropzone/fetch', 'GalleryController@fetch')->name('dropzone.fetch');
    Route::get('dropzone/delete', 'GalleryController@delete')->name('dropzone.delete');
    Route::get('getfile/{id}', 'GalleryController@getfile')->name('getfile');

});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Blog extends Model
{
    use SoftDeletes;
    
    protected $fillable=[
        'category_id', 'image','description','content','author','title','status','published_at'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Blog;
use Illuminate\Http\Request;
use App\Http\Requests\Blog\CreateBlogRequest;
use App\Http\Requests\Blog\UpdateBlogRequest;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('blog.index')->with('blogs',Blog::limit(5)
                ->get());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blog.create')->with('categories',Category::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBlogRequest $request)
    {
        //dd($request);

        $image=$request->image->store('posts');

        if(empty($request->published_at)){
            $request->published_at=date('yy-m-d');
        }

        Blog::create([
            'category_id'=>$request->category,
            'image'=>$image,
            'description'=>$request->description,
            'content'=>$request->content,
            'author'=>$request->author,
            'title'=>$request->title,
            'status'=>'1',
            'published_at'=>$request->published_at,
        ]);

        session()->flash('success','Post Created Successfully');
        return redirect(route('blog.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(blog $blog)
    {
        return view('blog.create')->with('blog',$blog)->with('categories',Category::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBlogRequest $request, Blog $blog)
    {
        if(empty($request->published_at)){
            $request->published_at=date('yyyy-mm-dd');
        }
        
        $data=$request->only(['title','description','published_at','author','content','category']);
        if($request->hasFile('image')){
            $image=$request->image->store('posts');
            $blog->deleteImage();
            $data['image']=$image;
        }
        
        $blog->update($data);

        session()->flash('success','Post Updated Successfully');
        return redirect(route('blog.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        $blog->deleteImage();
        $blog->delete();

        session()->flash('success','Post Deleted Successfully');
        return redirect(route('blog.index'));
    }
}

resources/views/blog/create.blade.php
@extends('layouts.app')

@section('content')


        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between g-3">
                <div class="nk-block-head-content">
                    <h2 class="nk-block-title page-title">{{ isset($blog)?'Update':'Add' }} Post</h2>
                    <div class="nk-block-des text-soft">
                        * are required.
                    </div>
                </div>
                
                <div class="nk-block-head-content">
                    <ul class="nk-block-tools g-3">
                        <li class="nk-block-tools-opt">
                            <a href="{{ route('blog.index') }}" class="btn btn-primary">
                                <em class="icon ni ni-arrow-left"></em>
                                <span>Back</span>
                            </a>
                        </li>
                    </ul>
                </div><!-- .nk-block-head-content -->
            </div><!-- .nk-block-head -->
        </div><!-- .nk-block-head -->
            
        @include('partials.session')
        @include('partials.error')
        
        <div class="nk-block nk-block-lg">
            <div class="card card-bordered">
                <div class="card-inner">
                    <div class="card-head">
                        <h5 class="card-title">New Post Setup</h5>
                    </div>
                    <form action="{{ isset($blog)? route('blog.update',$blog->id):route('blog.store') }}" class="gy-3" class="is-alter form-validate" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if (isset($blog))
                            {{ method_field('PUT') }}
                        @endif
                        <div class="row g-4">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-label">Action Category *</label>
                                    <div class="form-control-wrap">
                                        <select class="form-select form-control form-control-lg" name="category" id="category" data-search="on">
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}"
                                                    @if (isset($post))
                                                        @if ($category->id==$post->category_id)
                                                            selected
                                                        @endif
                                                    @endif
                                                >{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-label" for="image">Cover *</label>
                                    <div class="form-control-wrap">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" name="image" id="image" value="{{ isset($blog)?$blog->image:old('image')}}">
                                            <label class="custom-file-label" for="image">Choose file</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-label" for="title">Action Title *</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="title" id="title" value="{{ isset($blog)?$blog->title:old('title') }}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-label" for="description">Short Description *</label>
                                    <div class="form-control-wrap">
                                        <textarea class="form-control"  name="description" id="description" cols="30" rows="2">
                                            {{ isset($blog)?$blog->description:old('description')}}
                                        </textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-label" for="pay-amount-1">Post Content *</label>
                                    <div class="form-control-wrap">
                                        <textarea class="form-control"  name="content" id="content" cols="30" rows="10">
                                            {{ isset($blog)?$blog->content:old('content') }}
                                        </textarea>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-label" for="author">Author *</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="author" id="author"  value="{{ isset($blog)?$blog->author:'Dreamron' }}" value="{{ old('author') }}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-label" for="published_at">Published Date *</label>
                                    <div class="form-control-wrap">
                                        <input type="text" name="published_at" id="published_at" data-date-format="yyyy-mm-dd" class="form-control date-picker" value="{{ isset($blog)?$blog->published_at:'' }}">
                                    </div>
                                </div>
                            </div>

                            @if (isset($blog))
                            <div class="form-group">
                                <img src="{{ asset('storage/'.$blog->image) }}" style="width:100%">
                            </div>
                            @endif

                    
                            <div class="col-12">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-primary"><em class="icon ni ni-save"></em><span>Save</span> </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- .nk-block -->
@endsection

@section('script')
    <script type="text/javascript">
        CKEDITOR.replace('content', {
            filebrowserUploadUrl: "{{route('ckeditor.upload', ['_token' => csrf_token() ])}}",
            filebrowserUploadMethod: 'form'
        });
    </script>
@endsection

@section('css')

    <script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="nk-block-head nk-block-head-sm">
        <div class="nk-block-between g-3">
            <div class="nk-block-head-content">
                <h3 class="nk-block-title page-title">Blog Posts</h3>
                <div class="nk-block-des text-soft">
                    <p>You have total {{$blogs->count()}} posts.</p>
                </div>
            </div><!-- .nk-block-head-content -->
            <div class="nk-block-head-content">
                <ul class="nk-block-tools g-3">
                    <li>
                        <div class="drodown">
                            
                            <a href="{{ route('blog.create') }}" class="btn btn-primary">
                                <em class="icon ni ni-plus"></em>
                                <span>Add New Action</span>
                            </a>
                        </div>
                    </li>
                </ul>
            </div><!-- .nk-block-head-content -->
        </div><!-- .nk-block-between -->
    </div><!-- .nk-block-head -->

    
    @include('partials.error')
    
    @include('partials.session')
    
    <div class="nk-block nk-block-lg">
        <div class="card card-preview">
            <div class="card-inner">
                <table class="datatable-init nk-tb-list nk-tb-ulist" data-auto-responsive="false" id="blogs">
                    <thead>
                        <tr class="nk-tb-item nk-tb-head">
                            <th class="nk-tb-col "><span class="sub-text">#</span></th>
                            <th class="nk-tb-col"><span class="sub-text">Title</span></th>
                            <th class="nk-tb-col tb-col-mb"><span class="sub-text">Category</span></th>
                            <th class="nk-tb-col tb-col-lg"><span class="sub-text">Created at</span></th>
                            <th class="nk-tb-col tb-col-md"><span class="sub-text">Status</span></th>
                            <th class="nk-tb-col nk-tb-col-tools text-right">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $i=1;
                        @endphp
                        @foreach ($blogs->reverse() as $blog)
                            <tr class="nk-tb-item">
                                <td class="nk-tb-col tb-col-md">
                                    <span>{{ $i }}</span>
                                </td>
                                <td class="nk-tb-col">
                                    <div class="user-card">
                                        <div class="user-avatar bg-dim-primary d-none d-sm-flex">
                                            <img src="{{ asset('storage/'.$blog->image) }}" style="overflow: hidden; width:50px; height:50px" alt="">
                                        </div>
                                        <div class="user-info">
                                            <span class="tb-lead">{{ substr($blog->title,0,25) }} <span class="dot dot-success d-md-none ml-1"></span></span>
                                            <span>Action</span>
                                        </div>
                                    </div>
                                </td>
                                <td class="nk-tb-col tb-col-md">
                                    <span>{{ $blog->category_id }}</span>
                                </td>
                                <td class="nk-tb-col tb-col-md">
                                    <span>{{ date('d M Y', strtotime($blog->published_at)) }}</span>
                                </td>
                                <td class="nk-tb-col tb-col-md">
                                    @if ($blog->status=='1')
                                        <span class="tb-status text-success">Published
                                    @else
                                        <span class="tb-status text-warning">Draft
                                    @endif </span>
                                </td>
                                <td class="nk-tb-col nk-tb-col-tools">
                                    <ul class="nk-tb-actions gx-1">
                                        <li>
                                            <div class="drodown">
                                                <a href="#" class="dropdown-toggle btn btn-icon btn-trigger" data-toggle="dropdown"><em class="icon ni ni-more-h"></em></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <ul class="link-list-opt no-bdr">
                                                        <li><a href="{{ route('blog.edit',$blog->id) }}"><em class="icon ni ni-eye-alt"></em><span>Edit</span></a></li>
                                                        <li><a role="button" onclick="handleDelete({{$blog->id}})"><em class="icon ni ni-trash"></em><span>Remove</span></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </td>
                            </tr><!-- .nk-tb-item  -->
                            @php
                                $i++;
                            @endphp
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div><!-- .card-preview -->
    </div> <!-- nk-block -->

    <!-- Modal Alert -->
    <div class="modal fade" tabindex="-1"  role="dialog" id="deleteModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="post" id="deleteform">
            {{ method_field('DELETE') }}
            {{ csrf_field() }}
                <div class="modal-content">
                    <a href="#" class="close" data-dismiss="modal"><em class="icon ni ni-cross"></em></a>
                    <div class="modal-body modal-body-lg text-center">
                        <div class="nk-modal">
                            <em class="nk-modal-icon icon icon-circle icon-circle-xxl ni ni-alert bg-warning"></em>
                            <h4 class="nk-modal-title">Delete Action!</h4>
                            <div class="nk-modal-text">
                                <div class="caption-text">Are you sure, you want to <strong>delete</strong> this action ?</div>
                                <span class="sub-text-sm">This action can not be revert.</span>
                            </div>
                            <div class="nk-modal-action">
                                <button type="button" class="btn-lg btn-mw btn-primary" data-dismiss="modal">No, Go back</button>
                                <button type="submit" class="btn-lg btn-mw btn-danger">Yes, Delete</button>
                            </div>
                        </div>
                    </div><!-- .modal-body -->
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function handleDelete(id){
            var form= document.getElementById('deleteform')
            form.action='/blog/'+id
            $('#deleteModal').modal('show')
        }

    </script> 
@endsection