routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','SiteController@index')->name('welcome');
Route::get('/homepage','SiteController@homepage')->name('homepage');
Route::get('/product','SiteController@product')->name('product');
Route::get('/rnd','SiteController@rnd')->name('rnd');
Route::get('/oem','SiteController@oem')->name('oem');
Route::get('/contact','SiteController@contact')->name('contact');
Route::get('/story','SiteController@story')->name('story');
Route::get('/blogs','SiteController@blog')->name('blogs');
Route::get('/galleryshow','SiteController@galleryshow')->name('galleryshow');
Route::get('/albumshow/{album}','SiteController@albumshow')->name('albumshow');
Route::post('/contactmail','SiteController@contactmail')->name('contactmail');
Route::get('/loadproducts','SiteController@loadproducts')->name('loadproducts');
Route::post('/search','SiteController@search')->name('search');
Route::get('/thisyear','SiteController@thisyear')->name('thisyear');
Route::get('/pastyear','SiteController@pastyear')->name('pastyear');
Route::get('/nextyear','SiteController@nextyear')->name('nextyear');
Route::get('/jan/{blog}','SiteController@jan')->name('jan');
Route::get('/feb/{blog}','SiteController@feb')->name('feb');
Route::get('/mar/{blog}','SiteController@mar')->name('mar');
Route::get('/apr/{blog}','SiteController@apr')->name('apr');
Route::get('/may/{blog}','SiteController@may')->name('may');
Route::get('/jun/{blog}','SiteController@jun')->name('jun');
Route::get('/jul/{blog}','SiteController@jul')->name('jul');
Route::get('/aug/{blog}','SiteController@aug')->name('aug');
Route::get('/sep/{blog}','SiteController@sep')->name('sep');
Route::get('/oct/{blog}','SiteController@oct')->name('oct');
Route::get('/nov/{blog}','SiteController@nov')->name('nov');
Route::get('/dec/{blog}','SiteController@dec')->name('dec');
Route::get('/view/{blog}','SiteController@view')->name('view');

Route::get('/launched','SiteController@launched')->name('launched');

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('blog', 'BlogController');
    Route::resource('brands', 'BrandsController');
    Route::resource('categories', 'CategoriesController'); 
    Route::resource('subcategories', 'SubCategoriesController'); 
    Route::resource('products', 'ProductController'); 
    Route::get('getSubCat/{id}', 'ProductController@GetSubCat');
    Route::put('productimage', 'ProductController@productimage')->name('products.productimage'); 
    Route::get('productimageset/{product}', 'ProductController@productimageset')->name('products.productimageset');
    Route::post('productstatus/{product}', 'ProductController@status')->name('products.status'); 
    Route::get('passwordreset', 'UsersController@passwordreset')->name('passwordreset'); 
    Route::get('changepwd/{user}', 'UsersController@changepwd')->name('changepwd'); 
    Route::get('ckeditor', 'CkeditorController@index');
    Route::post('ckeditor/upload', 'CkeditorController@upload')->name('ckeditor.upload');   

    Route::get('/album','AlbumController@index')->name('album.index');
    Route::get('/album-getdata','AlbumController@getdata')->name('album.getdata');
    Route::post('/album/add','AlbumController@add')->name('album.add');
    Route::post('/album/edit','AlbumController@edit')->name('album.edit');
    Route::post('/album/delete','AlbumController@delete')->name('album.delete');

    Route::get('album-images/{album}','GalleryController@images')->name('album.images');
    Route::post('dropzone/upload', 'GalleryController@upload')->name('dropzone.upload');
    Route::get('dropzone/fetch', 'GalleryController@fetch')->name('dropzone.fetch');
    Route::get('dropzone/delete', 'GalleryController@delete')->name('dropzone.delete');
    Route::get('getfile/{id}', 'GalleryController@getfile')->name('getfile');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Product extends Model
{
    protected $fillable=[
        'category_id','subcategory_id','brand_id','name','sku','image','description','status','amount',
        'url','barcode'
    ];

    public function brand(){
        return $this->belongsTo(Brand::class);
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function subcategory(){
        return $this->belongsTo(SubCategory::class);
    }

    public function deleteImage(){
        Storage::delete($this->image);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Brand;
use App\Category;
use App\SubCategory;
use App\Product;
use App\Http\Requests\Product\ProductsCreateController;
use App\Http\Requests\Product\ProductsUpdateController;
use DB;
use Image;

class ProductController extends Controller
{
    public function GetSubCat($id){
        echo json_encode(DB::table('sub_categories')->where('category_id', $id)->get());
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products.index')->with('products',Product::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create')
        ->with('brands',Brand::all())
        ->with('categories',Category::all())
        ->with('subcategories',SubCategory::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductsCreateController $request)
    {

        $product=Product::create([
            'category_id'=>$request->category_id,
            'subcategory_id'=>$request->subcategory_id,
            'brand_id'=>$request->brand_id,
            'name'=>$request->name,
            'sku'=>$request->sku,
            'description'=>$request->description,
            'status'=>1,
            'amount'=>$request->amount,
            'url'=>$request->url,
            'barcode'=>$request->barcode,
        ]);

        session()->flash('success','Product Created Successfully');
        return redirect(route('products.productimageset',$product->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.create')
        ->with('product',$product)
        ->with('brands',Brand::all())
        ->with('categories',Category::all())
        ->with('subcategories',SubCategory::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductsUpdateController $request, Product $product)
    {
        $data=$request->only(['category_id','subcategory_id','brand_id','name','url','barcode','sku','description','status','amount']);

        $product->update($data);

        session()->flash('success','Product Updated Successfully');
        return redirect(route('products.productimageset',$product->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->deleteImage();
        $product->delete();

        session()->flash('success','Product Deleted Successfully');
        return redirect(route('products.index'));

    }

    public function productimageset(Product $product){
        return view('products.image')
        ->with('product',$product);
    }

    public function productimage(Request $request){
        //get filename with extension
        $filenamewithextension = $request->file('image')->getClientOriginalName();

        //get filename without extension
        $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);
    
        //get file extension
        $extension = $request->file('image')->getClientOriginalExtension();
    
        //filename to store
        $filenametostore = $filename.'_'.time().'.'.$extension;
    
        $img = Image::make($request->file('image'));
        $croppath = 'storage/products/'.$filenametostore;
        $croppath_save = 'products/'.$filenametostore;
        if(!is_null($request->input('w'))){
            $img->crop($request->input('w'), $request->input('h'), $request->input('x1'), $request->input('y1'))->resize(300, 300);    
        }
        $img->save($croppath);


        $data['image']=$croppath_save;
        $product=Product::find($request->id);
        $product->deleteImage();
        $product->update($data);

        session()->flash('success','Product Updated');
        return redirect(route('products.index'));

    }

    public function status(Product $product){
        if($product->status=='1'){            
            $product->status='0';
            $product->save();
            session()->flash('success','Product Saved as draft');
        }
        else{
            $product->status='1';
            $product->save();
            session()->flash('success','Product Published');
        }
        return redirect(route('products.index'));
    }


}

resources/views/products/create.blade.php
@extends('layouts.app')


@section('content')


        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between g-3">
                <div class="nk-block-head-content">
                    <h2 class="nk-block-title page-title">{{ isset($product)?'Update':'Add' }} Product</h2>
                    <div class="nk-block-des text-soft">
                        * are required.
                    </div>
                </div>
                
                <div class="nk-block-head-content">
                    <ul class="nk-block-tools g-3">
                        <li class="nk-block-tools-opt">
                            <a href="{{ route('products.index') }}" class="btn btn-primary">
                                <em class="icon ni ni-arrow-left"></em>
                                <span>Back</span>
                            </a>
                        </li>
                    </ul>
                </div><!-- .nk-block-head-content -->
            </div><!-- .nk-block-head -->
        </div><!-- .nk-block-head -->
            
        @include('partials.session')
        @include('partials.error')
        
        <div class="nk-block nk-block-lg">
            <div class="card card-bordered">
                <div class="card-inner">
                    <div class="card-head">
                        <h5 class="card-title">{{ isset($product)?'Edit':'New' }} Product Setup</h5>
                    </div>
                    <form action="{{ isset($product)? route('products.update',$product->id):route('products.store') }}" class="gy-3" class="is-alter form-validate" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if (isset($product))
                            {{ method_field('PUT') }}
                        @endif
                        <div class="row g-4">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="form-label" for="is_headline">Brand *</label>
                                    <div class="form-control-wrap">
                                        <select name="brand_id" id="brand_id" class="form-select" >
                                            <option value="0" disabled selected>Select Brand *</option>
                                            @foreach ($brands as $brand)
                                                <option value="{{ $brand->id }}"
                                                    @if (isset($product))
                                                        @if ($brand->id==$product->brand_id)
                                                            selected
                                                        @endif
                                                    @endif
                                                    >{{ $brand->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="form-label" for="is_headline">Category *</label>
                                    <div class="form-control-wrap">
                                        <select name="category_id" id="category_id" class="form-select" >
                                            <option value="0" disabled selected>Select Category*</option>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->id }}"
                                                    @if (isset($product))
                                                        @if ($category->id==$product->category_id)
                                                            selected
                                                        @endif
                                                    @endif
                                                    >{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="form-label" for="is_headline">Sub Category</label>
                                    <div class="form-control-wrap">
                                        <select name="subcategory_id" id="subcategory_id" class="form-select" >
                                            <option value="0" disabled>Select Sub Category*</option>
                                            @if (isset($product))
                                                @foreach ($subcategories as $category)
                                                    <option value="{{ $category->id }}"
                                                        @if (isset($product))
                                                            @if ($category->id==$product->subcategory_id)
                                                                selected
                                                            @endif
                                                        @endif
                                                        >{{ $category->name }}</option>
                                                @endforeach
                                            @endif

                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-label" for="name">Product Name *</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="name" id="name" value="{{ isset($product)?$product->name:old('name') }}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-label" for="description">Product Description *</label>
                                    <div class="form-control-wrap">
                                        <textarea class="form-control"  name="description" id="description" cols="30" rows="2">{{ isset($product)?$product->description:old('description')}}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-label" for="amount">Amount</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="amount" id="amount" value="{{ isset($product)?$product->amount:old('amount') }}">
                                    </div>
                                </div>
                            </div><!--
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-label" for="sku">SKU</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="sku" id="sku" value="{{ isset($product)?$product->sku:old('sku') }}">
                                    </div>
                                </div>
                            </div>-->
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="form-label" for="barcode">Barcode</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="barcode" id="barcode" value="{{ isset($product)?$product->barcode:old('barcode') }}">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="form-label" for="url">URL</label>
                                    <div class="form-control-wrap">
                                        <input type="text" class="form-control" name="url" id="url" value="{{ isset($product)?$product->url:old('url') }}">
                                    </div>
                                </div>
                            </div>

                            @if (isset($product))
                            <div class="form-group">
                                <img src="{{ asset('storage/'.$product->image) }}" style="width: 100%" >
                            </div>
                            @endif
                            
                    
                            <div class="col-12">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-primary"><em class="icon ni ni-save"></em><span>Save & Next</span> </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- .nk-block -->
@endsection

@section('script')
    
   

<script type="text/javascript">

    
    $(document).ready(function () {
            



        $('#category_id').on('change', function () {
            let id = $(this).val();
            $('#subcategory_id').empty();
            $.ajax({
                type: 'GET',
                url: 'getSubCat/' + id,
                success: function (response) {
                    var response = JSON.parse(response); 
                    $('#subcategory_id').empty();
                    $('#subcategory_id').append(`<option value="0" disabled selected>Select Sub Category*</option>`);
                    response.forEach(element => {
                        $('#subcategory_id').append(`<option value="${element['id']}">${element['name']}</option>`);
                    });
                }
            });
        });
    });


</script>
@endsection

resources/views/products/image.blade.php
@extends('layouts.app')

@section('css')
    <link rel="stylesheet" href="{{ asset('css/imgareaselect.css') }}" />
@endsection

@section('content')


        <div class="nk-block-head nk-block-head-sm">
            <div class="nk-block-between g-3">
                <div class="nk-block-head-content">
                <h2 class="nk-block-title page-title">{{  isset($product->image)?'Update':'Add' }} Product Image for {{ $product->name }}</h2>
                    <div class="nk-block-des text-soft">
                        * are required.
                    </div>
                </div>
                
                <div class="nk-block-head-content">
                    <ul class="nk-block-tools g-3">
                        <li class="nk-block-tools-opt">
                            <a href="{{ route('products.edit',$product->id) }}" class="btn btn-primary">
                                <em class="icon ni ni-arrow-left"></em>
                                <span>Back</span>
                            </a>
                        </li>
                    </ul>
                </div><!-- .nk-block-head-content -->
            </div><!-- .nk-block-head -->
        </div><!-- .nk-block-head -->
            
        @include('partials.session')
        @include('partials.error')
        
        <div class="nk-block nk-block-lg">
            <div class="card card-bordered">
                <div class="card-inner">
                    <div class="card-head">
                        <h5 class="card-title">{{ isset($product)?'Edit':'New' }} Upload Product Image and Crop</h5>
                    </div>
                    <form action="{{ isset($product)? route('products.productimage'):'' }}" class="gy-3" class="is-alter form-validate" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        @if (isset($product))
                            {{ method_field('PUT') }}
                        @endif
                        <div class="row g-4">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <input type="hidden" name="id" value="{{ $product->id }}">
                                    <label class="form-label" for="image">Image *</label>
                                    <div class="form-control-wrap">
                                        <div class="custom-file">
                                            <input type="file" class="image custom-file-input" name="image" id="image" value="{{ isset($product)?$product->image:old('image')}}">
                                            <label class="custom-file-label" for="image">Choose file</label>
                                                    
                                            <input type="hidden" name="x1" value="" />
                                            <input type="hidden" name="y1" value="" />
                                            <input type="hidden" name="w" value="" />
                                            <input type="hidden" name="h" value="" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            
                            <div class="row mt-5">
                                <p><img id="previewimage" style="display:none;"/></p>
                                @if(session('path'))
                                    <img src="{{ session('path') }}" />
                                @endif
                            </div>
                    
                            <div class="col-12">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-lg btn-primary"><em class="icon ni ni-save"></em><span>Save</span> </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div><!-- .nk-block -->
@endsection

@section('script')
    
   
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/imgareaselect/0.9.10/js/jquery.imgareaselect.min.js"></script>
<script>

    

    jQuery(function($) {
        var p = $("#previewimage");

        $("body").on("change", ".image", function(){
            var imageReader = new FileReader();
            imageReader.readAsDataURL(document.querySelector(".image").files[0]);

            imageReader.onload = function (oFREvent) {
                p.attr('src', oFREvent.target.result).fadeIn();
            };
        });

        $('#previewimage').imgAreaSelect({
            aspectRatio: '1:1', 
            handles: true ,
            onSelectEnd: function (img, selection) {
                $('input[name="x1"]').val(selection.x1);
                $('input[name="y1"]').val(selection.y1);
                $('input[name="w"]').val(selection.width);
                $('input[name="h"]').val(selection.height);            
            }
        });
    });



    


</script>
@endsection